- name: Install Keystone in Ubuntu
  apt:
    name:
      - keystone
      - apache2
      - php
      - libapache2-mod-php
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
